// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateTenantData, CreateTenantResponses, ExpireEnrollmentData, ExpireEnrollmentResponses, GetTenantData, GetTenantResponses, InviteOperatorData, InviteOperatorResponses, ListPendingEnrollmentsData, ListPendingEnrollmentsResponses, ListTenantsData, ListTenantsResponses, RedeemEnrollmentData, RedeemEnrollmentResponses, RestoreTenantData, RestoreTenantResponses, SoftDeleteTenantData, SoftDeleteTenantResponses, SuspendTenantData, SuspendTenantResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List tenants
 */
export const listTenants = <ThrowOnError extends boolean = true>(options?: Options<ListTenantsData, ThrowOnError>) => (options?.client ?? client).get<ListTenantsResponses, unknown, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/admin/orgs',
    ...options
});

/**
 * Create tenant
 */
export const createTenant = <ThrowOnError extends boolean = true>(options?: Options<CreateTenantData, ThrowOnError>) => (options?.client ?? client).post<CreateTenantResponses, unknown, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/admin/orgs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Soft-delete tenant
 */
export const softDeleteTenant = <ThrowOnError extends boolean = true>(options: Options<SoftDeleteTenantData, ThrowOnError>) => (options.client ?? client).delete<SoftDeleteTenantResponses, unknown, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/admin/orgs/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get tenant by id
 */
export const getTenant = <ThrowOnError extends boolean = true>(options: Options<GetTenantData, ThrowOnError>) => (options.client ?? client).get<GetTenantResponses, unknown, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/admin/orgs/{id}',
    ...options
});

/**
 * Suspend tenant
 */
export const suspendTenant = <ThrowOnError extends boolean = true>(options: Options<SuspendTenantData, ThrowOnError>) => (options.client ?? client).post<SuspendTenantResponses, unknown, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/admin/orgs/{id}/suspend',
    ...options
});

/**
 * Restore tenant
 */
export const restoreTenant = <ThrowOnError extends boolean = true>(options: Options<RestoreTenantData, ThrowOnError>) => (options.client ?? client).post<RestoreTenantResponses, unknown, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/admin/orgs/{id}/restore',
    ...options
});

/**
 * List pending enrollments
 */
export const listPendingEnrollments = <ThrowOnError extends boolean = true>(options?: Options<ListPendingEnrollmentsData, ThrowOnError>) => (options?.client ?? client).get<ListPendingEnrollmentsResponses, unknown, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/admin/operator-enroll',
    ...options
});

/**
 * Invite operator
 */
export const inviteOperator = <ThrowOnError extends boolean = true>(options?: Options<InviteOperatorData, ThrowOnError>) => (options?.client ?? client).post<InviteOperatorResponses, unknown, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/admin/operator-enroll',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Redeem enrollment token
 */
export const redeemEnrollment = <ThrowOnError extends boolean = true>(options: Options<RedeemEnrollmentData, ThrowOnError>) => (options.client ?? client).post<RedeemEnrollmentResponses, unknown, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/admin/operator-enroll/{token}/redeem',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Expire enrollment
 */
export const expireEnrollment = <ThrowOnError extends boolean = true>(options: Options<ExpireEnrollmentData, ThrowOnError>) => (options.client ?? client).post<ExpireEnrollmentResponses, unknown, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/admin/operator-enroll/{id}/expire',
    ...options
});
