// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3100' | (string & {});
};

export type ListTenantsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number | null;
    };
    url: '/api/admin/orgs';
};

export type ListTenantsResponses = {
    /**
     * Tenants list
     */
    200: {
        rows: Array<{
            id: string;
            slug: string | null;
            name: string;
            enforceSSO: boolean;
            sessionVersion: number;
            suspendedAt: string | null;
            deletedAt: string | null;
            createdAt: string;
        }>;
        total: number;
        limit: number;
        offset: number;
    };
};

export type ListTenantsResponse = ListTenantsResponses[keyof ListTenantsResponses];

export type CreateTenantData = {
    body?: {
        slug: string;
        name?: string;
        enforceSSO?: boolean;
        branding?: {
            logoVersion: number;
            primaryColor: string;
            appName: string;
        };
    };
    path?: never;
    query?: never;
    url: '/api/admin/orgs';
};

export type CreateTenantResponses = {
    /**
     * Tenant created
     */
    201: {
        row: {
            id: string;
            slug: string | null;
            name: string;
            enforceSSO: boolean;
            sessionVersion: number;
            suspendedAt: string | null;
            deletedAt: string | null;
            createdAt: string;
        };
    };
};

export type CreateTenantResponse = CreateTenantResponses[keyof CreateTenantResponses];

export type SoftDeleteTenantData = {
    body?: {
        confirm: true;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/orgs/{id}';
};

export type SoftDeleteTenantResponses = {
    /**
     * Tenant tombstoned
     */
    200: {
        tombstoned: {
            id: string;
            slug: string | null;
        };
    };
};

export type SoftDeleteTenantResponse = SoftDeleteTenantResponses[keyof SoftDeleteTenantResponses];

export type GetTenantData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/orgs/{id}';
};

export type GetTenantResponses = {
    /**
     * Tenant row
     */
    200: {
        row: {
            id: string;
            slug: string | null;
            name: string;
            enforceSSO: boolean;
            sessionVersion: number;
            suspendedAt: string | null;
            deletedAt: string | null;
            createdAt: string;
        };
    };
};

export type GetTenantResponse = GetTenantResponses[keyof GetTenantResponses];

export type SuspendTenantData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/orgs/{id}/suspend';
};

export type SuspendTenantResponses = {
    /**
     * Tenant suspended
     */
    200: {
        row: {
            id: string;
            slug: string | null;
            name: string;
            enforceSSO: boolean;
            sessionVersion: number;
            suspendedAt: string | null;
            deletedAt: string | null;
            createdAt: string;
        };
    };
};

export type SuspendTenantResponse = SuspendTenantResponses[keyof SuspendTenantResponses];

export type RestoreTenantData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/orgs/{id}/restore';
};

export type RestoreTenantResponses = {
    /**
     * Tenant restored
     */
    200: {
        row: {
            id: string;
            slug: string | null;
            name: string;
            enforceSSO: boolean;
            sessionVersion: number;
            suspendedAt: string | null;
            deletedAt: string | null;
            createdAt: string;
        };
    };
};

export type RestoreTenantResponse = RestoreTenantResponses[keyof RestoreTenantResponses];

export type ListPendingEnrollmentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/operator-enroll';
};

export type ListPendingEnrollmentsResponses = {
    /**
     * Pending enrollments
     */
    200: {
        rows: Array<{
            id: string;
            email: string;
            subRole: 'platform_admin' | 'support' | 'read_only';
            expiresAt: string | null;
            invitedAt: string;
        }>;
    };
};

export type ListPendingEnrollmentsResponse = ListPendingEnrollmentsResponses[keyof ListPendingEnrollmentsResponses];

export type InviteOperatorData = {
    body?: {
        email: string;
        subRole: 'platform_admin' | 'support' | 'read_only';
        ttlDays?: number;
    };
    path?: never;
    query?: never;
    url: '/api/admin/operator-enroll';
};

export type InviteOperatorResponses = {
    /**
     * Invite issued
     */
    201: {
        enrollmentId: string;
        token: string;
        expiresAt: string;
    };
};

export type InviteOperatorResponse = InviteOperatorResponses[keyof InviteOperatorResponses];

export type RedeemEnrollmentData = {
    body?: {
        password: string;
        displayName?: string;
        token?: string;
    };
    path: {
        token: string;
    };
    query?: never;
    url: '/api/admin/operator-enroll/{token}/redeem';
};

export type RedeemEnrollmentResponses = {
    /**
     * Enrollment redeemed
     */
    200: {
        enrollmentId: string;
        userId: string;
        email: string;
        subRole: 'platform_admin' | 'support' | 'read_only';
    };
};

export type RedeemEnrollmentResponse = RedeemEnrollmentResponses[keyof RedeemEnrollmentResponses];

export type ExpireEnrollmentData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/operator-enroll/{id}/expire';
};

export type ExpireEnrollmentResponses = {
    /**
     * Enrollment expired
     */
    200: {
        enrollmentId: string;
    };
};

export type ExpireEnrollmentResponse = ExpireEnrollmentResponses[keyof ExpireEnrollmentResponses];
