// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zListTenantsQuery = z.object({
    limit: z.int().gte(1).lte(200).optional(),
    offset: z.int().gte(0).nullish()
});

/**
 * Tenants list
 */
export const zListTenantsResponse = z.object({
    rows: z.array(z.object({
        id: z.string(),
        slug: z.string().nullable(),
        name: z.string(),
        enforceSSO: z.boolean(),
        sessionVersion: z.int().gte(0),
        suspendedAt: z.string().nullable(),
        deletedAt: z.string().nullable(),
        createdAt: z.string()
    })),
    total: z.int().gte(0),
    limit: z.int().gt(0),
    offset: z.int().gte(0)
});

export const zCreateTenantBody = z.object({
    slug: z.string().min(1).max(63).regex(/^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/),
    name: z.string().min(1).max(120).optional(),
    enforceSSO: z.boolean().optional(),
    branding: z.object({
        logoVersion: z.int().gte(0),
        primaryColor: z.string().min(1),
        appName: z.string().min(1)
    }).optional()
});

/**
 * Tenant created
 */
export const zCreateTenantResponse = z.object({
    row: z.object({
        id: z.string(),
        slug: z.string().nullable(),
        name: z.string(),
        enforceSSO: z.boolean(),
        sessionVersion: z.int().gte(0),
        suspendedAt: z.string().nullable(),
        deletedAt: z.string().nullable(),
        createdAt: z.string()
    })
});

export const zSoftDeleteTenantBody = z.object({
    confirm: z.literal(true)
});

export const zSoftDeleteTenantPath = z.object({
    id: z.string().min(1)
});

/**
 * Tenant tombstoned
 */
export const zSoftDeleteTenantResponse = z.object({
    tombstoned: z.object({
        id: z.string(),
        slug: z.string().nullable()
    })
});

export const zGetTenantPath = z.object({
    id: z.string().min(1)
});

/**
 * Tenant row
 */
export const zGetTenantResponse = z.object({
    row: z.object({
        id: z.string(),
        slug: z.string().nullable(),
        name: z.string(),
        enforceSSO: z.boolean(),
        sessionVersion: z.int().gte(0),
        suspendedAt: z.string().nullable(),
        deletedAt: z.string().nullable(),
        createdAt: z.string()
    })
});

export const zSuspendTenantPath = z.object({
    id: z.string().min(1)
});

/**
 * Tenant suspended
 */
export const zSuspendTenantResponse = z.object({
    row: z.object({
        id: z.string(),
        slug: z.string().nullable(),
        name: z.string(),
        enforceSSO: z.boolean(),
        sessionVersion: z.int().gte(0),
        suspendedAt: z.string().nullable(),
        deletedAt: z.string().nullable(),
        createdAt: z.string()
    })
});

export const zRestoreTenantPath = z.object({
    id: z.string().min(1)
});

/**
 * Tenant restored
 */
export const zRestoreTenantResponse = z.object({
    row: z.object({
        id: z.string(),
        slug: z.string().nullable(),
        name: z.string(),
        enforceSSO: z.boolean(),
        sessionVersion: z.int().gte(0),
        suspendedAt: z.string().nullable(),
        deletedAt: z.string().nullable(),
        createdAt: z.string()
    })
});

/**
 * Pending enrollments
 */
export const zListPendingEnrollmentsResponse = z.object({
    rows: z.array(z.object({
        id: z.string(),
        email: z.string(),
        subRole: z.enum([
            'platform_admin',
            'support',
            'read_only'
        ]),
        expiresAt: z.string().nullable(),
        invitedAt: z.string()
    }))
});

export const zInviteOperatorBody = z.object({
    email: z.email().max(254),
    subRole: z.enum([
        'platform_admin',
        'support',
        'read_only'
    ]),
    ttlDays: z.int().gte(1).lte(30).optional()
});

/**
 * Invite issued
 */
export const zInviteOperatorResponse = z.object({
    enrollmentId: z.string(),
    token: z.string(),
    expiresAt: z.string()
});

export const zRedeemEnrollmentBody = z.object({
    password: z.string().min(12).max(256),
    displayName: z.string().min(1).max(120).optional(),
    token: z.string().min(16).max(256).optional()
});

export const zRedeemEnrollmentPath = z.object({
    token: z.string().min(1)
});

/**
 * Enrollment redeemed
 */
export const zRedeemEnrollmentResponse = z.object({
    enrollmentId: z.string(),
    userId: z.string(),
    email: z.string(),
    subRole: z.enum([
        'platform_admin',
        'support',
        'read_only'
    ])
});

export const zExpireEnrollmentPath = z.object({
    id: z.string().min(1)
});

/**
 * Enrollment expired
 */
export const zExpireEnrollmentResponse = z.object({
    enrollmentId: z.string()
});
