// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createTenant, expireEnrollment, getTenant, inviteOperator, listPendingEnrollments, listTenants, type Options, redeemEnrollment, restoreTenant, softDeleteTenant, suspendTenant } from '../sdk.gen';
import type { CreateTenantData, CreateTenantResponse, ExpireEnrollmentData, ExpireEnrollmentResponse, GetTenantData, GetTenantResponse, InviteOperatorData, InviteOperatorResponse, ListPendingEnrollmentsData, ListPendingEnrollmentsResponse, ListTenantsData, ListTenantsResponse, RedeemEnrollmentData, RedeemEnrollmentResponse, RestoreTenantData, RestoreTenantResponse, SoftDeleteTenantData, SoftDeleteTenantResponse, SuspendTenantData, SuspendTenantResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const listTenantsQueryKey = (options?: Options<ListTenantsData>) => createQueryKey('listTenants', options);

/**
 * List tenants
 */
export const listTenantsOptions = (options?: Options<ListTenantsData>) => queryOptions<ListTenantsResponse, DefaultError, ListTenantsResponse, ReturnType<typeof listTenantsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => await listTenants({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
    }),
    queryKey: listTenantsQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const listTenantsInfiniteQueryKey = (options?: Options<ListTenantsData>): QueryKey<Options<ListTenantsData>> => createQueryKey('listTenants', options, true);

/**
 * List tenants
 */
export const listTenantsInfiniteOptions = (options?: Options<ListTenantsData>) => infiniteQueryOptions<ListTenantsResponse, DefaultError, InfiniteData<ListTenantsResponse>, QueryKey<Options<ListTenantsData>>, number | null | Pick<QueryKey<Options<ListTenantsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ListTenantsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                offset: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        return await listTenants({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
    },
    queryKey: listTenantsInfiniteQueryKey(options)
});

/**
 * Create tenant
 */
export const createTenantMutation = (options?: Partial<Options<CreateTenantData>>): UseMutationOptions<CreateTenantResponse, DefaultError, Options<CreateTenantData>> => {
    const mutationOptions: UseMutationOptions<CreateTenantResponse, DefaultError, Options<CreateTenantData>> = {
        mutationFn: async (fnOptions) => await createTenant({
            ...options,
            ...fnOptions,
            throwOnError: true
        })
    };
    return mutationOptions;
};

/**
 * Soft-delete tenant
 */
export const softDeleteTenantMutation = (options?: Partial<Options<SoftDeleteTenantData>>): UseMutationOptions<SoftDeleteTenantResponse, DefaultError, Options<SoftDeleteTenantData>> => {
    const mutationOptions: UseMutationOptions<SoftDeleteTenantResponse, DefaultError, Options<SoftDeleteTenantData>> = {
        mutationFn: async (fnOptions) => await softDeleteTenant({
            ...options,
            ...fnOptions,
            throwOnError: true
        })
    };
    return mutationOptions;
};

export const getTenantQueryKey = (options: Options<GetTenantData>) => createQueryKey('getTenant', options);

/**
 * Get tenant by id
 */
export const getTenantOptions = (options: Options<GetTenantData>) => queryOptions<GetTenantResponse, DefaultError, GetTenantResponse, ReturnType<typeof getTenantQueryKey>>({
    queryFn: async ({ queryKey, signal }) => await getTenant({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
    }),
    queryKey: getTenantQueryKey(options)
});

/**
 * Suspend tenant
 */
export const suspendTenantMutation = (options?: Partial<Options<SuspendTenantData>>): UseMutationOptions<SuspendTenantResponse, DefaultError, Options<SuspendTenantData>> => {
    const mutationOptions: UseMutationOptions<SuspendTenantResponse, DefaultError, Options<SuspendTenantData>> = {
        mutationFn: async (fnOptions) => await suspendTenant({
            ...options,
            ...fnOptions,
            throwOnError: true
        })
    };
    return mutationOptions;
};

/**
 * Restore tenant
 */
export const restoreTenantMutation = (options?: Partial<Options<RestoreTenantData>>): UseMutationOptions<RestoreTenantResponse, DefaultError, Options<RestoreTenantData>> => {
    const mutationOptions: UseMutationOptions<RestoreTenantResponse, DefaultError, Options<RestoreTenantData>> = {
        mutationFn: async (fnOptions) => await restoreTenant({
            ...options,
            ...fnOptions,
            throwOnError: true
        })
    };
    return mutationOptions;
};

export const listPendingEnrollmentsQueryKey = (options?: Options<ListPendingEnrollmentsData>) => createQueryKey('listPendingEnrollments', options);

/**
 * List pending enrollments
 */
export const listPendingEnrollmentsOptions = (options?: Options<ListPendingEnrollmentsData>) => queryOptions<ListPendingEnrollmentsResponse, DefaultError, ListPendingEnrollmentsResponse, ReturnType<typeof listPendingEnrollmentsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => await listPendingEnrollments({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
    }),
    queryKey: listPendingEnrollmentsQueryKey(options)
});

/**
 * Invite operator
 */
export const inviteOperatorMutation = (options?: Partial<Options<InviteOperatorData>>): UseMutationOptions<InviteOperatorResponse, DefaultError, Options<InviteOperatorData>> => {
    const mutationOptions: UseMutationOptions<InviteOperatorResponse, DefaultError, Options<InviteOperatorData>> = {
        mutationFn: async (fnOptions) => await inviteOperator({
            ...options,
            ...fnOptions,
            throwOnError: true
        })
    };
    return mutationOptions;
};

/**
 * Redeem enrollment token
 */
export const redeemEnrollmentMutation = (options?: Partial<Options<RedeemEnrollmentData>>): UseMutationOptions<RedeemEnrollmentResponse, DefaultError, Options<RedeemEnrollmentData>> => {
    const mutationOptions: UseMutationOptions<RedeemEnrollmentResponse, DefaultError, Options<RedeemEnrollmentData>> = {
        mutationFn: async (fnOptions) => await redeemEnrollment({
            ...options,
            ...fnOptions,
            throwOnError: true
        })
    };
    return mutationOptions;
};

/**
 * Expire enrollment
 */
export const expireEnrollmentMutation = (options?: Partial<Options<ExpireEnrollmentData>>): UseMutationOptions<ExpireEnrollmentResponse, DefaultError, Options<ExpireEnrollmentData>> => {
    const mutationOptions: UseMutationOptions<ExpireEnrollmentResponse, DefaultError, Options<ExpireEnrollmentData>> = {
        mutationFn: async (fnOptions) => await expireEnrollment({
            ...options,
            ...fnOptions,
            throwOnError: true
        })
    };
    return mutationOptions;
};
