#!/usr/bin/env bun
// biome-ignore-all lint/suspicious/noConsole: CLI script — console output is the interface.
/**
 * Seed `.env` files from the canonical env-key spec.
 *
 * Existing files are preserved: missing keys are appended under a dated marker
 * so a re-run never clobbers operator-tuned values.
 *
 * Reads `ENV_KEY_SPECS` (a hand-maintained table next to `envSchema`)
 * rather than reaching into Zod's `_def`. A `env-schema.spec.ts` drift
 * test keeps the two in sync.
 *
 * Usage:
 *   bun run setup:env
 *
 * Optional env overrides (used by tests for isolation):
 *   SETUP_ENV_ROOT — repo root to seed (defaults to the repo containing this script)
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { ENV_KEY_SPECS, type KeySpec } from "../apps/server/src/env-schema";

type EmittedSpec =
  | { kind: "default"; value: string }
  | { kind: "optional" }
  | { kind: "required" };

type Target = {
  path: string;
  keys: readonly string[];
};

const NEWLINE_RE = /\r?\n/;

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const DEFAULT_ROOT = resolve(SCRIPT_DIR, "..");

function toEmittedSpec(spec: KeySpec): EmittedSpec {
  if (spec.default !== undefined) {
    return { kind: "default", value: spec.default };
  }
  return spec.required ? { kind: "required" } : { kind: "optional" };
}

function buildKeyMap(): Map<string, EmittedSpec> {
  const out = new Map<string, EmittedSpec>();
  for (const [key, spec] of Object.entries(ENV_KEY_SPECS)) {
    out.set(key, toEmittedSpec(spec));
  }
  return out;
}

function renderLine(key: string, spec: EmittedSpec): string {
  if (spec.kind === "default") {
    return `${key}=${spec.value}`;
  }
  if (spec.kind === "required") {
    return `# REQUIRED\n${key}=`;
  }
  return `${key}=`;
}

function parseExistingKeys(contents: string): Set<string> {
  const present = new Set<string>();
  for (const rawLine of contents.split(NEWLINE_RE)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) {
      continue;
    }
    const eq = line.indexOf("=");
    if (eq <= 0) {
      continue;
    }
    present.add(line.slice(0, eq).trim());
  }
  return present;
}

function renderFresh(
  keys: readonly string[],
  specs: Map<string, EmittedSpec>
): string {
  const lines: string[] = [];
  lines.push("# Generated by bun run setup:env");
  lines.push(
    "# Edit freely — re-running the script never overwrites existing keys."
  );
  lines.push("");
  for (const key of keys) {
    const spec = specs.get(key);
    if (!spec) {
      continue;
    }
    lines.push(renderLine(key, spec));
  }
  lines.push("");
  return lines.join("\n");
}

function renderAddendum(
  missing: readonly string[],
  specs: Map<string, EmittedSpec>,
  today: string
): string {
  const lines: string[] = [];
  lines.push("");
  lines.push(`# Added by setup:env on ${today}`);
  for (const key of missing) {
    const spec = specs.get(key);
    if (!spec) {
      continue;
    }
    lines.push(renderLine(key, spec));
  }
  lines.push("");
  return lines.join("\n");
}

function ensureTrailingNewline(text: string): string {
  return text.endsWith("\n") ? text : `${text}\n`;
}

function processTarget(
  target: Target,
  specs: Map<string, EmittedSpec>,
  today: string
): "created" | "updated" | "unchanged" {
  if (!existsSync(target.path)) {
    writeFileSync(target.path, renderFresh(target.keys, specs), "utf8");
    return "created";
  }

  const existing = readFileSync(target.path, "utf8");
  const present = parseExistingKeys(existing);
  const missing = target.keys.filter((key) => !present.has(key));

  if (missing.length === 0) {
    return "unchanged";
  }

  const next =
    ensureTrailingNewline(existing) + renderAddendum(missing, specs, today);
  writeFileSync(target.path, next, "utf8");
  return "updated";
}

function todayIso(): string {
  return new Date().toISOString().slice(0, 10);
}

function computeTargets(root: string, allKeys: readonly string[]): Target[] {
  const targets: Target[] = [{ path: join(root, ".env"), keys: allKeys }];

  const adminPath = join(root, "apps", "admin-server");
  if (existsSync(adminPath)) {
    targets.push({ path: join(adminPath, ".env"), keys: allKeys });
  }

  return targets;
}

export type SetupEnvResult = {
  root: string;
  outcomes: Array<{
    path: string;
    status: "created" | "updated" | "unchanged";
  }>;
};

export function runSetupEnv(rootOverride?: string): SetupEnvResult {
  const root = rootOverride ?? process.env.SETUP_ENV_ROOT ?? DEFAULT_ROOT;
  const specs = buildKeyMap();
  const allKeys = [...specs.keys()];
  const targets = computeTargets(root, allKeys);
  const today = todayIso();

  const outcomes = targets.map((target) => ({
    path: target.path,
    status: processTarget(target, specs, today),
  }));

  return { root, outcomes };
}

const isDirectInvocation = import.meta.url === `file://${process.argv[1]}`;
if (isDirectInvocation) {
  const result = runSetupEnv();
  for (const outcome of result.outcomes) {
    console.log(`${outcome.status.padEnd(9)} ${outcome.path}`);
  }
}
